/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CareerRouteImport } from './routes/career'
import { Route as BuildRouteImport } from './routes/build'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiStudioRouteImport } from './routes/ai-studio'
import { Route as IndexRouteImport } from './routes/index'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/blog': typeof BlogRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/certifications': typeof CertificationsRoute
  '/community': typeof CommunityRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/blog': typeof BlogRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/certifications': typeof CertificationsRoute
  '/community': typeof CommunityRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/blog': typeof BlogRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/certifications': typeof CertificationsRoute
  '/community': typeof CommunityRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-studio'
    | '/blog'
    | '/build'
    | '/career'
    | '/certifications'
    | '/community'
    | '/company'
    | '/dashboard'
    | '/learn'
    | '/practice'
    | '/resources'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-studio'
    | '/blog'
    | '/build'
    | '/career'
    | '/certifications'
    | '/community'
    | '/company'
    | '/dashboard'
    | '/learn'
    | '/practice'
    | '/resources'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/ai-studio'
    | '/blog'
    | '/build'
    | '/career'
    | '/certifications'
    | '/community'
    | '/company'
    | '/dashboard'
    | '/learn'
    | '/practice'
    | '/resources'
    | '/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiStudioRoute: typeof AiStudioRoute
  BlogRoute: typeof BlogRoute
  BuildRoute: typeof BuildRoute
  CareerRoute: typeof CareerRoute
  CertificationsRoute: typeof CertificationsRoute
  CommunityRoute: typeof CommunityRoute
  CompanyRoute: typeof CompanyRoute
  DashboardRoute: typeof DashboardRoute
  LearnRoute: typeof LearnRoute
  PracticeRoute: typeof PracticeRoute
  ResourcesRoute: typeof ResourcesRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio': {
      id: '/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiStudioRoute: AiStudioRoute,
  BlogRoute: BlogRoute,
  BuildRoute: BuildRoute,
  CareerRoute: CareerRoute,
  CertificationsRoute: CertificationsRoute,
  CommunityRoute: CommunityRoute,
  CompanyRoute: CompanyRoute,
  DashboardRoute: DashboardRoute,
  LearnRoute: LearnRoute,
  PracticeRoute: PracticeRoute,
  ResourcesRoute: ResourcesRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
