/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CareerRouteImport } from './routes/career'
import { Route as BuildRouteImport } from './routes/build'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiStudioRouteImport } from './routes/ai-studio'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunitySectionSlugRouteImport } from './routes/community_.$sectionSlug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AiStudioAgentIdRouteImport } from './routes/ai-studio_.$agentId'
import { Route as AdminSectionSlugRouteImport } from './routes/admin_.$sectionSlug'
import { Route as LearnPathsPathSlugRouteImport } from './routes/learn_.paths.$pathSlug'
import { Route as LearnCoursesCourseSlugRouteImport } from './routes/learn_.courses.$courseSlug'
import { Route as LearnCoursesCourseSlugLessonSlugRouteImport } from './routes/learn_.courses.$courseSlug.$lessonSlug'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySectionSlugRoute = CommunitySectionSlugRouteImport.update({
  id: '/community_/$sectionSlug',
  path: '/community/$sectionSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioAgentIdRoute = AiStudioAgentIdRouteImport.update({
  id: '/ai-studio_/$agentId',
  path: '/ai-studio/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionSlugRoute = AdminSectionSlugRouteImport.update({
  id: '/admin_/$sectionSlug',
  path: '/admin/$sectionSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPathsPathSlugRoute = LearnPathsPathSlugRouteImport.update({
  id: '/learn_/paths/$pathSlug',
  path: '/learn/paths/$pathSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCoursesCourseSlugRoute = LearnCoursesCourseSlugRouteImport.update({
  id: '/learn_/courses/$courseSlug',
  path: '/learn/courses/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCoursesCourseSlugLessonSlugRoute =
  LearnCoursesCourseSlugLessonSlugRouteImport.update({
    id: '/$lessonSlug',
    path: '/$lessonSlug',
    getParentRoute: () => LearnCoursesCourseSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-studio': typeof AiStudioRoute
  '/blog': typeof BlogRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/certifications': typeof CertificationsRoute
  '/community': typeof CommunityRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
  '/admin/$sectionSlug': typeof AdminSectionSlugRoute
  '/ai-studio/$agentId': typeof AiStudioAgentIdRoute
  '/api/chat': typeof ApiChatRoute
  '/community/$sectionSlug': typeof CommunitySectionSlugRoute
  '/learn/courses/$courseSlug': typeof LearnCoursesCourseSlugRouteWithChildren
  '/learn/paths/$pathSlug': typeof LearnPathsPathSlugRoute
  '/learn/courses/$courseSlug/$lessonSlug': typeof LearnCoursesCourseSlugLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-studio': typeof AiStudioRoute
  '/blog': typeof BlogRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/certifications': typeof CertificationsRoute
  '/community': typeof CommunityRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
  '/admin/$sectionSlug': typeof AdminSectionSlugRoute
  '/ai-studio/$agentId': typeof AiStudioAgentIdRoute
  '/api/chat': typeof ApiChatRoute
  '/community/$sectionSlug': typeof CommunitySectionSlugRoute
  '/learn/courses/$courseSlug': typeof LearnCoursesCourseSlugRouteWithChildren
  '/learn/paths/$pathSlug': typeof LearnPathsPathSlugRoute
  '/learn/courses/$courseSlug/$lessonSlug': typeof LearnCoursesCourseSlugLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-studio': typeof AiStudioRoute
  '/blog': typeof BlogRoute
  '/build': typeof BuildRoute
  '/career': typeof CareerRoute
  '/certifications': typeof CertificationsRoute
  '/community': typeof CommunityRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/practice': typeof PracticeRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
  '/admin_/$sectionSlug': typeof AdminSectionSlugRoute
  '/ai-studio_/$agentId': typeof AiStudioAgentIdRoute
  '/api/chat': typeof ApiChatRoute
  '/community_/$sectionSlug': typeof CommunitySectionSlugRoute
  '/learn_/courses/$courseSlug': typeof LearnCoursesCourseSlugRouteWithChildren
  '/learn_/paths/$pathSlug': typeof LearnPathsPathSlugRoute
  '/learn_/courses/$courseSlug/$lessonSlug': typeof LearnCoursesCourseSlugLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-studio'
    | '/blog'
    | '/build'
    | '/career'
    | '/certifications'
    | '/community'
    | '/company'
    | '/dashboard'
    | '/learn'
    | '/practice'
    | '/resources'
    | '/support'
    | '/admin/$sectionSlug'
    | '/ai-studio/$agentId'
    | '/api/chat'
    | '/community/$sectionSlug'
    | '/learn/courses/$courseSlug'
    | '/learn/paths/$pathSlug'
    | '/learn/courses/$courseSlug/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-studio'
    | '/blog'
    | '/build'
    | '/career'
    | '/certifications'
    | '/community'
    | '/company'
    | '/dashboard'
    | '/learn'
    | '/practice'
    | '/resources'
    | '/support'
    | '/admin/$sectionSlug'
    | '/ai-studio/$agentId'
    | '/api/chat'
    | '/community/$sectionSlug'
    | '/learn/courses/$courseSlug'
    | '/learn/paths/$pathSlug'
    | '/learn/courses/$courseSlug/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-studio'
    | '/blog'
    | '/build'
    | '/career'
    | '/certifications'
    | '/community'
    | '/company'
    | '/dashboard'
    | '/learn'
    | '/practice'
    | '/resources'
    | '/support'
    | '/admin_/$sectionSlug'
    | '/ai-studio_/$agentId'
    | '/api/chat'
    | '/community_/$sectionSlug'
    | '/learn_/courses/$courseSlug'
    | '/learn_/paths/$pathSlug'
    | '/learn_/courses/$courseSlug/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiStudioRoute: typeof AiStudioRoute
  BlogRoute: typeof BlogRoute
  BuildRoute: typeof BuildRoute
  CareerRoute: typeof CareerRoute
  CertificationsRoute: typeof CertificationsRoute
  CommunityRoute: typeof CommunityRoute
  CompanyRoute: typeof CompanyRoute
  DashboardRoute: typeof DashboardRoute
  LearnRoute: typeof LearnRoute
  PracticeRoute: typeof PracticeRoute
  ResourcesRoute: typeof ResourcesRoute
  SupportRoute: typeof SupportRoute
  AdminSectionSlugRoute: typeof AdminSectionSlugRoute
  AiStudioAgentIdRoute: typeof AiStudioAgentIdRoute
  ApiChatRoute: typeof ApiChatRoute
  CommunitySectionSlugRoute: typeof CommunitySectionSlugRoute
  LearnCoursesCourseSlugRoute: typeof LearnCoursesCourseSlugRouteWithChildren
  LearnPathsPathSlugRoute: typeof LearnPathsPathSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio': {
      id: '/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community_/$sectionSlug': {
      id: '/community_/$sectionSlug'
      path: '/community/$sectionSlug'
      fullPath: '/community/$sectionSlug'
      preLoaderRoute: typeof CommunitySectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio_/$agentId': {
      id: '/ai-studio_/$agentId'
      path: '/ai-studio/$agentId'
      fullPath: '/ai-studio/$agentId'
      preLoaderRoute: typeof AiStudioAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/$sectionSlug': {
      id: '/admin_/$sectionSlug'
      path: '/admin/$sectionSlug'
      fullPath: '/admin/$sectionSlug'
      preLoaderRoute: typeof AdminSectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/paths/$pathSlug': {
      id: '/learn_/paths/$pathSlug'
      path: '/learn/paths/$pathSlug'
      fullPath: '/learn/paths/$pathSlug'
      preLoaderRoute: typeof LearnPathsPathSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/courses/$courseSlug': {
      id: '/learn_/courses/$courseSlug'
      path: '/learn/courses/$courseSlug'
      fullPath: '/learn/courses/$courseSlug'
      preLoaderRoute: typeof LearnCoursesCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/courses/$courseSlug/$lessonSlug': {
      id: '/learn_/courses/$courseSlug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/learn/courses/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof LearnCoursesCourseSlugLessonSlugRouteImport
      parentRoute: typeof LearnCoursesCourseSlugRoute
    }
  }
}

interface LearnCoursesCourseSlugRouteChildren {
  LearnCoursesCourseSlugLessonSlugRoute: typeof LearnCoursesCourseSlugLessonSlugRoute
}

const LearnCoursesCourseSlugRouteChildren: LearnCoursesCourseSlugRouteChildren =
  {
    LearnCoursesCourseSlugLessonSlugRoute:
      LearnCoursesCourseSlugLessonSlugRoute,
  }

const LearnCoursesCourseSlugRouteWithChildren =
  LearnCoursesCourseSlugRoute._addFileChildren(
    LearnCoursesCourseSlugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiStudioRoute: AiStudioRoute,
  BlogRoute: BlogRoute,
  BuildRoute: BuildRoute,
  CareerRoute: CareerRoute,
  CertificationsRoute: CertificationsRoute,
  CommunityRoute: CommunityRoute,
  CompanyRoute: CompanyRoute,
  DashboardRoute: DashboardRoute,
  LearnRoute: LearnRoute,
  PracticeRoute: PracticeRoute,
  ResourcesRoute: ResourcesRoute,
  SupportRoute: SupportRoute,
  AdminSectionSlugRoute: AdminSectionSlugRoute,
  AiStudioAgentIdRoute: AiStudioAgentIdRoute,
  ApiChatRoute: ApiChatRoute,
  CommunitySectionSlugRoute: CommunitySectionSlugRoute,
  LearnCoursesCourseSlugRoute: LearnCoursesCourseSlugRouteWithChildren,
  LearnPathsPathSlugRoute: LearnPathsPathSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
